[package]
name = "cce-secrets"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { path = "../cce-ui" }
calloop = "0.13.0"
wayland-client = { version = "0.31", features = ["system"] }
tokio = { version = "1", features = ["full"] }
secret-service = { version = "5", features = ["rt-tokio-crypto-rust"] }
zbus = "5"
log = "0.4"
env_logger = "0.11"
